ShiftsSchedule/src/ShiftsSchedule/ViewComponents/ShiftsDateListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShiftsSchedule.Models.ViewModels;
using ShiftsSchedule.Models.Repository;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;

namespace ShiftsSchedule.ViewComponents
{
    public class ShiftsDateListViewComponent : ViewComponent
    {
        private readonly WorkersRepository _repoWkr;
        private ProjectsRepository _repoPrj;

        public ShiftsDateListViewComponent(WorkersRepository repoWrk, ProjectsRepository repoPrj)
        {
            _repoWkr = repoWrk;
            _repoPrj = repoPrj;
        }

        public IViewComponentResult Invoke(int? workerId, int? projectId)
        {
            var items = GetItems(workerId, projectId);
            return View(items);
        }
        private IEnumerable<ShiftsViewModel> GetItems(int? workerId, int? projectId)
        {
            if (workerId != null)
            {
                return Mapper.Map<IEnumerable<ShiftsViewModel>>(_repoWkr.GetWorkerShifts((int)workerId));
            }
            else if (projectId != null)
            {
                var project = _repoPrj.FindBy(p => p.Id == projectId).FirstOrDefault();
                return Mapper.Map<IEnumerable<ShiftsViewModel>>((project.Shifts.ToList()));
            }
            else return new List<ShiftsViewModel>();
        }

    }
}

ShiftsSchedule/src/ShiftsSchedule/Views/Workers/Components/WorkersList/Default.cshtml
@model IEnumerable<WorkersViewModel>
@{ 
    CultureInfo myCulture = new CultureInfo("en-US");
}
<table class="table table-striped table-responsive">

    <thead>
        <tr>
            <th>Name</th>
            <th>Specialty</th>
            <th>Salary</th>
            <th class="ctrtxt">Shifts Attending</th>
            <th class="ctrtxt">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var worker in Model)
        {
            <tr>
                <td>@worker.Name</td>

          @*   <td>@worker.Specialty.Name</td>*@

                <td>
                    @worker.Salary.ToString("C", myCulture)/hour
                </td>

                <td>@await Component.InvokeAsync("ShiftsDateList", new { workerId = worker.Id })</td>
                <td class="ctrtxt">
                    <a asp-action="Edit" asp-route-id="@worker.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a id="btn-delete-worker" data-worker-id="@worker.Id" class="js-delete-worker btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>


        }
    </tbody>
</table>