ShiftsSchedule/src/ShiftsSchedule/Controllers/Api/ShiftsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShiftsSchedule.Models;
using ShiftsSchedule.Models.Repository;
using ShiftsSchedule.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;

namespace ShiftsSchedule.Controllers.Api
{
    [Route("api/projects/{projectId}/shifts")]
    public class ShiftsController : ApiController
    {
        private ProjectsRepository _repository;
        private ILogger<ShiftsController> _logger;
    

        public ShiftsController(ProjectsRepository repository, ILogger<ShiftsController> logger)
        {
            _repository = repository;
            _logger = logger;
        }
        //GET
        [HttpGet("")]
        public IActionResult Get(int projectId)
        {
            try
            {  
                var project = _repository.FindBy(p => p.Id == projectId).FirstOrDefault();
                return Ok(Mapper.Map<IEnumerable<ShiftsViewModel>>(project.Shifts.ToList()));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to get all shifts for project: {ex.Message}");
                return Redirect("/error");
            }
        }
        
        //DELETE
        [HttpDelete("delete/{shiftId}")]
        public async Task<IActionResult> Delete(int shiftId)
        {
            if (ModelState.IsValid)
            {
                _repository.DeleteShift(shiftId);
                if (await _repository.SaveChangesAsync())
                {
                    return Ok();
                }
            }

            _logger.LogError($"Failed to delete shift with id {shiftId}");
            return Redirect("/error");
        }

    }
}

ShiftsSchedule/src/ShiftsSchedule/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shifts Schedule</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootswatch/slate/bootstrap.css" />
        <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="text-info">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-form" style="height: 120%">
                    <li>
                        <i>
                            <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                                <i class="fa fa-chevron-circle-left"></i>
                                Shifts Schedule 
                                <i class="fa fa-chevron-circle-right"></i>
                            </a>
                        </i>
                   
                    </li>
                    <li><a class="btn" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.Identity.IsAuthenticated && (User.IsInRole("admins") || User.IsInRole("operators")))
                    {
                        <li><a class="btn" asp-controller="Workers" asp-action="Workers">Workers</a></li>
                        <li><a class="btn" asp-controller="Shifts" asp-action="Shifts">Shifts</a></li>
                    }
                    @if (User.Identity.IsAuthenticated && User.IsInRole("workers"))
                    {
                        <li><a class="btn btn-warning" asp-controller="Shifts" asp-action="Calendar">My Shifts</a></li>
                        <li><a class="btn btn-success" asp-controller="Projects" asp-action="Projects">Projects</a></li>
                    }

                    @if (User.Identity.IsAuthenticated && User.IsInRole("admins"))
                    {
                        <li><a class="btn" asp-controller="Projects" asp-action="Projects">Projects</a></li>
                        <li><a class="btn btn-success" asp-controller="Account" asp-action="Admin">Admin</a></li>

                    }

                    <li><a class="btn" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a class="btn" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()

    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootbox/bootbox.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

    </environment>
    @Html.Partial("_ValidationScriptsPartial")

    @RenderSection("scripts", required: false)

    <footer class="panel-footer navbar-fixed-bottom">
        <p style="text-align:center">&copy; 2016 - Shifts Schedule</p>
    </footer>

</body>

</html>